language: node_js
node_js:
  - "4.4.7"
script: "gulp travis"
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - "npm install codeclimate-test-reporter"
  - "codeclimate-test-reporter < coverage/lcov.info"
