module.exports = {
  DISMISS_SUBSCRIBE_POPUP: 'DISMISS_SUBSCRIBE_POPUP',
  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  TOGGLE_MENU_SUBITEMS: 'TOGGLE_MENU_SUBITEMS',

  FETCH_PRODUCTS: 'FETCH_PRODUCTS',

  FETCH_PRODUCT: 'FETCH_PRODUCT',
  OPEN_MEASUREMENTS_POPUP: 'OPEN_MEASUREMENTS_POPUP',
  CLOSE_MEASUREMENTS_POPUP: 'CLOSE_MEASUREMENTS_POPUP',
  PICK_PRODUCT_COLOR: 'PICK_PRODUCT_COLOR',
  SET_PRODUCT_MEASUREMENTS: 'SET_PRODUCT_MEASUREMENTS',

  TOGGLE_QUICK_BAG: 'TOGGLE_QUICK_BAG',
  ADD_PRODUCT_TO_BAG: 'ADD_PRODUCT_TO_BAG',
  REMOVE_PRODUCT_FROM_BAG: 'REMOVE_PRODUCT_FROM_BAG',

  CHANGE_CUSTOMER: 'CHANGE_CUSTOMER',
  START_SAVING_CUSTOMER: 'START_SAVING_CUSTOMER',
  DONE_SAVING_CUSTOMER: 'DONE_SAVING_CUSTOMER',
  CANNOT_SAVE_CUSTOMER: 'CANNOT_SAVE_CUSTOMER'
};
