module.exports = {
  DISMISS_SUBSCRIBE_POPUP: 'DISMISS_SUBSCRIBE_POPUP',
  TOGGLE_QUICK_BAG: 'TOGGLE_QUICK_BAG',
  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  TOGGLE_MENU_SUBITEMS: 'TOGGLE_MENU_SUBITEMS',
  FETCH_PRODUCT: 'FETCH_PRODUCT',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  OPEN_MEASURES_POPUP: 'OPEN_MEASURES_POPUP',
  CLOSE_MEASURES_POPUP: 'CLOSE_MEASURES_POPUP'
};
